InvoiceBox/invoicebox-ui

src/components/common/WarningIcon/components/Icon.tsx
src/components/common/WarningIcon/index.stories.tsx
src/components/common/WarningIcon/index.tsx
src/components/common/WarningIcon/palette.ts
src/components/common/WarningIcon/styles.ts
src/index.ts
src/palette/context.tsx
src/palette/provider.tsx

warning icon

---

src/components/common/InvoiceboxSpinner/index.stories.tsx
src/components/common/InvoiceboxSpinner/index.tsx
src/components/common/InvoiceboxSpinner/palette.ts
src/components/common/SecondaryButton/index.tsx

Spinner убран модификатор в пользу palette

InvoiceboxSpinner

---

.gitignore
src/components/form/SearchInput/components/CrossIcon/index.stories.tsx
src/components/form/SearchInput/components/CrossIcon/index.tsx
src/components/form/SearchInput/components/SearchIcon/index.stories.tsx
src/components/form/SearchInput/components/SearchIcon/index.tsx
src/components/form/SearchInput/index.stories.tsx
src/components/form/SearchInput/index.tsx
src/components/form/SearchInput/palette.ts
src/components/form/SearchInput/styles.ts
src/index.ts
src/palette/context.tsx
src/palette/provider.tsx

- Добавил `SearchInput` компонент;
- Обновил `gitignore`.

search input

---

src/components/common/Flag/styles.ts
src/components/form/CountrySelect/components/CountryItem/index.stories.tsx
src/components/form/CountrySelect/components/CountryItem/index.tsx
src/components/form/CountrySelect/components/CountryItem/stlyes.ts
src/components/form/CountrySelect/index.stories.tsx
src/components/form/CountrySelect/index.tsx
src/components/form/CountrySelect/logic.ts
src/components/form/CountrySelect/palette.ts
src/components/form/CountrySelect/stlyes.ts
src/palette/context.tsx
src/palette/provider.tsx

CountrySelect component

---

src/components/form/Select/hooks/useOptionGroups.ts
src/components/form/Select/index.stories.tsx
src/components/form/Select/index.tsx
src/components/form/Select/styles.ts

В селект добавлена возможность группировки

Select groups

---

package-lock.json
package.json
src/components/common/Typography/index.tsx
src/components/form/PhoneInput/constants.ts
src/components/form/PhoneInput/hooks/useValidateInitialValue.ts
src/components/form/PhoneInput/index.stories.tsx
src/components/form/PhoneInput/index.tsx
src/components/form/PhoneInput/phoneInputLogic.ts
src/components/form/PhoneInput/styles.ts
src/components/form/PhoneInput/types.ts
src/components/form/PureInput/index.tsx
src/index.ts

phone input

---

src/components/form/PhoneInput/constants.ts
src/components/form/PhoneInput/hooks/useValidateInitialValue.ts
src/components/form/PhoneInput/index.tsx
src/components/form/PhoneInput/phoneInputLogic.ts

Сделано:
- Выключил автокомплит на инпуте телефона;
- Сделал чтобы при вводе телефона через "8" оно превращалось в "+7", при вводе через "9" превращалось в "+79".

phone autocomplete off, ru changer

---

src/components/miniApp/MiniAppWrapper/index.stories.tsx
src/components/miniApp/MiniAppWrapper/index.tsx
src/components/miniApp/MiniAppWrapper/styles.ts
src/index.ts

MiniAppWrapper

---

src/components/common/Scrollbar/index.stories.tsx
src/components/common/Scrollbar/index.tsx

По умолчанию `Scrollbar` имеет `maxHeight = '100%'`

scrollbar default maxHeight

---

src/components/form/PhoneInput/externalPhoneLogic.ts
src/components/form/PhoneInput/phoneInputLogic.ts
src/index.ts

external phone logic

---

src/components/common/Dropdown/index.tsx

disableCSSOMInjection in dropdown

disableCSSOMInjection in dropdown

---

package-lock.json
package.json
src/components/common/Dropdown/index.tsx

sc-peerDependencies

---

src/components/form/PhoneInput/externalPhoneLogic.ts

getIsValidRusPhone

---

src/index.ts
src/palette/index.ts

export `defaultAbstractPalette`

defaultAbstractPalette

---

src/components/common/BgCard/index.stories.tsx
src/components/common/BgCard/index.tsx
src/components/common/BgCard/styles.ts

isTopLeftBorder

---

src/components/common/InvoiceboxLoader/index.tsx

Убрано лишнее растояние у лоадера

InvoiceboxLoader fix

---

src/components/form/SearchInput/index.tsx

search input forward ref

---

src/components/form/PhoneInput/index.tsx

В мобильной версии выпадающий список стран в инпуте телефона растягивается по ширине инпута

phone-input-mobile-country-list-adaptive

---

src/components/common/SecondaryButton/index.stories.tsx
src/components/common/SecondaryButton/index.tsx
src/components/common/SecondaryButton/styles.ts

Завёл проп `size` для `SecondaryButton`

secondary-button-size

---

src/components/common/SecondaryButton/index.tsx
src/components/common/SecondaryButton/styles.ts

secondary-button-borderadius

---

src/components/common/SecondaryButton/index.tsx
src/components/common/SecondaryButton/styles.ts

padding props secondary button

padding props secondary button

---

src/components/form/SearchInput/index.tsx

New props for SearchInput component

SearchInput new props

---

src/components/form/PhoneInput/constants.ts
src/components/form/PhoneInput/index.stories.tsx
src/components/form/PhoneInput/index.tsx

kaz phone number validate fix

---

src/components/common/AppCardLink/index.stories.tsx
src/components/common/AppCardLink/index.tsx
src/components/common/InvoiceboxLogo/index.stories.tsx
src/components/common/InvoiceboxLogo/index.tsx
src/index.ts

fix exports

---

src/components/form/Autocomplete/components/Autocomplete/index.tsx

Autocomplete-input-max-length

---

src/components/form/TextInput/index.tsx
src/validate/index.ts

Ogrn validate

---

src/validate/index.ts

validate website

---

src/components/common/Toast/index.tsx

fix toast warnings in console

---

src/components/form/PhoneInput/index.tsx

Phone input have input mode for numeric values

PhoneInput-input-mode

---

src/components/common/Typography/index.tsx
src/components/form/PureInput/index.tsx
src/components/form/PureInput/styles.ts
src/components/form/TextInput/index.tsx

text input can be textarea

---

src/components/form/DateInput/index.stories.tsx
src/components/form/DateInput/index.tsx
src/components/form/DateInput/logic.ts
src/components/form/DateInput/styles.ts

DateInput have time

---

src/components/form/DateInput/index.tsx

Добавлено открытия окна дат по нажатию на поле ввода

add open dates popup by field click

---

src/components/form/Autocomplete/components/Autocomplete/index.tsx

Добавлена звездочка обязательного поля для компонента Autocomplete

I1-412 add required star for autocomplete
